### ISSUE TITLE
Error: write to file 6639af86aa32a827fd49b599d396fd7148577c38_03406_IBIZA_Z.PNG

### ISSUE THREAD

**Issue by davidverbeek** [Agence-DnD/PIMGento-API#39]
Hello Everyone.

I am having around 7500 products with images in Akeneo. Now When i import those products into magento 1.9 I am getting below errors after importing around 250 images

Error: write to file 6639af86aa32a827fd49b599d396fd7148577c38_03406_IBIZA_Z.PNG

It uploads some images around 250 but after that it is getting the above error.

Please let me know if there is any limit set for importing large number of  images.

![pimgento_image_issue](https://user-images.githubusercontent.com/50629081/72876400-6c164980-3d1c-11ea-9d81-2ed1b2bd2935.png)

When I run the import process using command prompt, I am getting below error

PHP Fatal error:  Uncaught Error: Class 'Task_Executor_Exception' not found in /var/www/html/onlinetest/app/code/community/Task/Executor/Model/Task.php:103
Stack trace:
#0 /var/www/html/onlinetest/shell/pimgento.php(238): Task_Executor_Model_Task->execute()
#1 /var/www/html/onlinetest/shell/pimgento.php(80): Mage_Shell_Pimgento->runImport('product')
#2 /var/www/html/onlinetest/shell/pimgento.php(255): Mage_Shell_Pimgento->run()
#3 {main}
  thrown in /var/www/html/onlinetest/app/code/community/Task/Executor/Model/Task.php on line 103

Fatal error: Uncaught Error: Class 'Task_Executor_Exception' not found in /var/www/html/onlinetest/app/code/community/Task/Executor/Model/Task.php:103
Stack trace:
#0 /var/www/html/onlinetest/shell/pimgento.php(238): Task_Executor_Model_Task->execute()
#1 /var/www/html/onlinetest/shell/pimgento.php(80): Mage_Shell_Pimgento->runImport('product')
#2 /var/www/html/onlinetest/shell/pimgento.php(255): Mage_Shell_Pimgento->run()
#3 {main}
  thrown in /var/www/html/onlinetest/app/code/community/Task/Executor/Model/Task.php on line 103

**Comment by davidverbeek** [comment]
I resolved the issue.. The issue was because the file was open using fopen but not closed. So I have added "$ioAdapter->streamClose();"  after "$ioAdapter->streamWrite($binary);" in saveMediaFile function.

Thanks.
